# NOTE: Generated By HttpRunner v3.1.6
# FROM: har\addSku.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseAddsku(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/fxm/services/local/fxm/product/product.japi")
            .post("https://mt.lhs11.com/fxm/services/local/fxm/product/product.japi")
            .with_headers(
                **{
                    "content-length": "216",
                    "sec-ch-ua": '" Not A;Brand";v="99", "Chromium";v="98", "Google Chrome";v="98"',
                    "accept": "application/json, text/javascript, */*; q=0.01",
                    "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "x-requested-with": "XMLHttpRequest",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36",
                    "sec-ch-ua-platform": '"Windows"',
                    "origin": "https://mt.lhs11.com",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mt.lhs11.com/fxm/page/fxm/product/dzm/addorupdate.jsp?action=update&product_id=5466&page=1",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8,en-US;q=0.7,zh-TW;q=0.6",
                }
            )
            .with_cookies(
                **{
                    "nginx-sticky": "1646806365.251.270.504776",
                    "JSESSIONID": "3F2375F28FE80C1651395FF487F95967",
                    "gr_user_id": "3b236d1c-48e6-4117-8e12-09d6e1b24927",
                    "UM_distinctid": "17d30b9ff81cc9-02185ea260576f-57b1a33-1fa400-17d30b9ff82c95",
                    "lhs-uscp-id": "1000000640",
                    "lhs-ucs-id": "12460",
                    "RSESSIONID": "DSHS6AU0CMMQ2WXDEJGUDETMEVGS7HHU",
                }
            )
            .with_data(
                {
                    '{"method":"sku_add","params":{"variables":{"id":"null","product_id":"5466","product_code":"CVFM8J","ordernum":"","listnum":"","allowmodify":"null","sku_id":"吐逗喜剧","sku_val_id":"单人门票","sort_num":"1"}}}': ""
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseAddsku().test_start()
