# NOTE: Generated By HttpRunner v3.1.4
# FROM: har\fxc4_homepage.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseFxc4Homepage(HttpRunner):

    config = Config("testcase description").verify(False).base_url("${ENV(BASEURL)}")

    teststeps = [
        Step(
            RunRequest("/v1/fxc4-api/login/config")
            .get("/v1/fxc4-api/login/config")
            .with_params(**{"env": "WXMP", "domain": "fx3-luoyang.lhs11.com"})
            .with_headers(
                **{
                    "user-token": "",
                    "frontendappid": "",
                    "env": "WXMP",
                    "user-agent": "Mozilla/5.0 (Linux; Android 6.0.1; MuMu Build/V417IR; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/68.0.3440.70 Mobile Safari/537.36 MMWEBID/77 MicroMessenger/7.0.22.1820(0x27001636) Process/tools WeChat/arm32 Weixin NetType/WIFI Language/zh_CN ABI/arm32",
                    "content-type": "application/json",
                    "accept": "*/*",
                    "referer": "https://fx3-luoyang.lhs11.com/fxc4-h5/",
                    "accept-encoding": "gzip, deflate",
                    "accept-language": "zh-CN,en-US;q=0.9",
                    "x-requested-with": "com.tencent.mm",
                }
            )
            .with_cookies(
                **{
                    "nginx-sticky": "1639816270.912.2299.391140",
                    "fx3-guangzhou.lhs11.com:ut": "${ENV(USERTOKEN)}",
                    "gr_user_id": "ff717bba-711e-4486-8fe1-ee35006320cd",
                    "fx3-pidu.lhs11.com:ut": "${ENV(USERTOKEN)}",
                    "fx3-luoyang.lhs11.com:ut": "${ENV(USERTOKEN)}",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.status", "success")
        ),
        Step(
            RunRequest("/v1/fxc4-api/home/allCities")
            .get("https://fx3-luoyang.lhs11.com/v1/fxc4-api/home/allCities")
            .with_params(**{"domain": "fx3-main.lhs11.com"})
            .with_headers(
                **{
                    "user-token": "${ENV(USERTOKEN)}",
                    "frontendappid": "wx8826cf59748f9d5b",
                    "env": "WXMP",
                    "user-agent": "Mozilla/5.0 (Linux; Android 6.0.1; MuMu Build/V417IR; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/68.0.3440.70 Mobile Safari/537.36 MMWEBID/77 MicroMessenger/7.0.22.1820(0x27001636) Process/tools WeChat/arm32 Weixin NetType/WIFI Language/zh_CN ABI/arm32",
                    "content-type": "application/json",
                    "accept": "*/*",
                    "referer": "https://fx3-luoyang.lhs11.com/fxc4-h5/",
                    "accept-encoding": "gzip, deflate",
                    "accept-language": "zh-CN,en-US;q=0.9",
                    "x-requested-with": "com.tencent.mm",
                }
            )
            .with_cookies(
                **{
                    "nginx-sticky": "1639816270.912.2299.391140",
                    "fx3-guangzhou.lhs11.com:ut": "${ENV(USERTOKEN)}",
                    "gr_user_id": "ff717bba-711e-4486-8fe1-ee35006320cd",
                    "fx3-pidu.lhs11.com:ut": "${ENV(USERTOKEN)}",
                    "fx3-luoyang.lhs11.com:ut": "${ENV(USERTOKEN)}",
                    "SERVERID": "cf2cc9c8ac39585fc0a0e28bf7f6523d|1639819157|1639819157",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.status", "success")
        ),
        Step(
            RunRequest("/v1/fxc4-api/customer/userRole")
            .get("https://fx3-luoyang.lhs11.com/v1/fxc4-api/customer/userRole")
            .with_headers(
                **{
                    "user-token": "${ENV(USERTOKEN)}",
                    "frontendappid": "wx8826cf59748f9d5b",
                    "env": "WXMP",
                    "user-agent": "Mozilla/5.0 (Linux; Android 6.0.1; MuMu Build/V417IR; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/68.0.3440.70 Mobile Safari/537.36 MMWEBID/77 MicroMessenger/7.0.22.1820(0x27001636) Process/tools WeChat/arm32 Weixin NetType/WIFI Language/zh_CN ABI/arm32",
                    "content-type": "application/json",
                    "accept": "*/*",
                    "referer": "https://fx3-luoyang.lhs11.com/fxc4-h5/",
                    "accept-encoding": "gzip, deflate",
                    "accept-language": "zh-CN,en-US;q=0.9",
                    "x-requested-with": "com.tencent.mm",
                }
            )
            .with_cookies(
                **{
                    "nginx-sticky": "1639816270.912.2299.391140",
                    "fx3-guangzhou.lhs11.com:ut": "${ENV(USERTOKEN)}",
                    "gr_user_id": "ff717bba-711e-4486-8fe1-ee35006320cd",
                    "fx3-pidu.lhs11.com:ut": "${ENV(USERTOKEN)}",
                    "fx3-luoyang.lhs11.com:ut": "${ENV(USERTOKEN)}",
                    "SERVERID": "cf2cc9c8ac39585fc0a0e28bf7f6523d|1639819157|1639819157",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.status", "success")
            .assert_equal("body.result", 0)
        ),
        Step(
            RunRequest("/v1/fxc4-api/customer/getCustomerInfo")
            .get("https://fx3-luoyang.lhs11.com/v1/fxc4-api/customer/getCustomerInfo")
            .with_headers(
                **{
                    "user-token": "${ENV(USERTOKEN)}",
                    "frontendappid": "wx8826cf59748f9d5b",
                    "env": "WXMP",
                    "user-agent": "Mozilla/5.0 (Linux; Android 6.0.1; MuMu Build/V417IR; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/68.0.3440.70 Mobile Safari/537.36 MMWEBID/77 MicroMessenger/7.0.22.1820(0x27001636) Process/tools WeChat/arm32 Weixin NetType/WIFI Language/zh_CN ABI/arm32",
                    "content-type": "application/json",
                    "accept": "*/*",
                    "referer": "https://fx3-luoyang.lhs11.com/fxc4-h5/",
                    "accept-encoding": "gzip, deflate",
                    "accept-language": "zh-CN,en-US;q=0.9",
                    "x-requested-with": "com.tencent.mm",
                }
            )
            .with_cookies(
                **{
                    "nginx-sticky": "1639816270.912.2299.391140",
                    "fx3-guangzhou.lhs11.com:ut": "${ENV(USERTOKEN)}",
                    "gr_user_id": "ff717bba-711e-4486-8fe1-ee35006320cd",
                    "fx3-pidu.lhs11.com:ut": "${ENV(USERTOKEN)}",
                    "fx3-luoyang.lhs11.com:ut": "${ENV(USERTOKEN)}",
                    "SERVERID": "cf2cc9c8ac39585fc0a0e28bf7f6523d|1639819157|1639819157",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.status", "success")
        ),
        Step(
            RunRequest("/v1/fxc4-api/activity/ad/find")
            .post("https://fx3-luoyang.lhs11.com/v1/fxc4-api/activity/ad/find")
            .with_headers(
                **{
                    "content-length": "65",
                    "origin": "https://fx3-luoyang.lhs11.com",
                    "user-token": "${ENV(USERTOKEN)}",
                    "frontendappid": "wx8826cf59748f9d5b",
                    "env": "WXMP",
                    "user-agent": "Mozilla/5.0 (Linux; Android 6.0.1; MuMu Build/V417IR; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/68.0.3440.70 Mobile Safari/537.36 MMWEBID/77 MicroMessenger/7.0.22.1820(0x27001636) Process/tools WeChat/arm32 Weixin NetType/WIFI Language/zh_CN ABI/arm32",
                    "content-type": "application/json",
                    "accept": "*/*",
                    "referer": "https://fx3-luoyang.lhs11.com/fxc4-h5/",
                    "accept-encoding": "gzip, deflate",
                    "accept-language": "zh-CN,en-US;q=0.9",
                    "x-requested-with": "com.tencent.mm",
                }
            )
            .with_cookies(
                **{
                    "nginx-sticky": "1639816270.912.2299.391140",
                    "fx3-guangzhou.lhs11.com:ut": "${ENV(USERTOKEN)}",
                    "gr_user_id": "ff717bba-711e-4486-8fe1-ee35006320cd",
                    "fx3-pidu.lhs11.com:ut": "${ENV(USERTOKEN)}",
                    "fx3-luoyang.lhs11.com:ut": "${ENV(USERTOKEN)}",
                    "SERVERID": "cf2cc9c8ac39585fc0a0e28bf7f6523d|1639819157|1639819157",
                }
            )
            .with_json(
                {"cityId": "95", "positionId": 1, "showType": "", "channelCode": "wxmp"}
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.status", "success")
        ),
        Step(
            RunRequest("/v1/fxc4-api/wechat/getJsSign")
            .get("https://fx3-luoyang.lhs11.com/v1/fxc4-api/wechat/getJsSign")
            .with_params(**{"portalId": "1032"})
            .with_headers(
                **{
                    "user-token": "${ENV(USERTOKEN)}",
                    "frontendappid": "wx8826cf59748f9d5b",
                    "env": "WXMP",
                    "user-agent": "Mozilla/5.0 (Linux; Android 6.0.1; MuMu Build/V417IR; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/68.0.3440.70 Mobile Safari/537.36 MMWEBID/77 MicroMessenger/7.0.22.1820(0x27001636) Process/tools WeChat/arm32 Weixin NetType/WIFI Language/zh_CN ABI/arm32",
                    "content-type": "application/json",
                    "accept": "*/*",
                    "referer": "https://fx3-luoyang.lhs11.com/fxc4-h5/",
                    "accept-encoding": "gzip, deflate",
                    "accept-language": "zh-CN,en-US;q=0.9",
                    "x-requested-with": "com.tencent.mm",
                }
            )
            .with_cookies(
                **{
                    "nginx-sticky": "1639816270.912.2299.391140",
                    "fx3-guangzhou.lhs11.com:ut": "${ENV(USERTOKEN)}",
                    "gr_user_id": "ff717bba-711e-4486-8fe1-ee35006320cd",
                    "fx3-pidu.lhs11.com:ut": "${ENV(USERTOKEN)}",
                    "fx3-luoyang.lhs11.com:ut": "${ENV(USERTOKEN)}",
                    "SERVERID": "cf2cc9c8ac39585fc0a0e28bf7f6523d|1639819157|1639819157",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.status", "success")
        ),
        Step(
            RunRequest("/v1/fxc4-api/home/getHomeShelf")
            .get("https://fx3-luoyang.lhs11.com/v1/fxc4-api/home/getHomeShelf")
            .with_params(**{"currentCityId": "95"})
            .with_headers(
                **{
                    "user-token": "${ENV(USERTOKEN)}",
                    "frontendappid": "wx8826cf59748f9d5b",
                    "env": "WXMP",
                    "user-agent": "Mozilla/5.0 (Linux; Android 6.0.1; MuMu Build/V417IR; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/68.0.3440.70 Mobile Safari/537.36 MMWEBID/77 MicroMessenger/7.0.22.1820(0x27001636) Process/tools WeChat/arm32 Weixin NetType/WIFI Language/zh_CN ABI/arm32",
                    "content-type": "application/json",
                    "accept": "*/*",
                    "referer": "https://fx3-luoyang.lhs11.com/fxc4-h5/",
                    "accept-encoding": "gzip, deflate",
                    "accept-language": "zh-CN,en-US;q=0.9",
                    "x-requested-with": "com.tencent.mm",
                }
            )
            .with_cookies(
                **{
                    "nginx-sticky": "1639816270.912.2299.391140",
                    "fx3-guangzhou.lhs11.com:ut": "${ENV(USERTOKEN)}",
                    "gr_user_id": "ff717bba-711e-4486-8fe1-ee35006320cd",
                    "fx3-pidu.lhs11.com:ut": "${ENV(USERTOKEN)}",
                    "fx3-luoyang.lhs11.com:ut": "${ENV(USERTOKEN)}",
                    "SERVERID": "cf2cc9c8ac39585fc0a0e28bf7f6523d|1639819158|1639819157",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.status", "success")
        ),
        Step(
            RunRequest("/v1/fxc4-api/customer/getCustomerInfo")
            .get("https://fx3-luoyang.lhs11.com/v1/fxc4-api/customer/getCustomerInfo")
            .with_headers(
                **{
                    "user-token": "${ENV(USERTOKEN)}",
                    "frontendappid": "wx8826cf59748f9d5b",
                    "env": "WXMP",
                    "user-agent": "Mozilla/5.0 (Linux; Android 6.0.1; MuMu Build/V417IR; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/68.0.3440.70 Mobile Safari/537.36 MMWEBID/77 MicroMessenger/7.0.22.1820(0x27001636) Process/tools WeChat/arm32 Weixin NetType/WIFI Language/zh_CN ABI/arm32",
                    "content-type": "application/json",
                    "accept": "*/*",
                    "referer": "https://fx3-luoyang.lhs11.com/fxc4-h5/",
                    "accept-encoding": "gzip, deflate",
                    "accept-language": "zh-CN,en-US;q=0.9",
                    "x-requested-with": "com.tencent.mm",
                }
            )
            .with_cookies(
                **{
                    "nginx-sticky": "1639816270.912.2299.391140",
                    "fx3-guangzhou.lhs11.com:ut": "${ENV(USERTOKEN)}",
                    "gr_user_id": "ff717bba-711e-4486-8fe1-ee35006320cd",
                    "fx3-pidu.lhs11.com:ut": "${ENV(USERTOKEN)}",
                    "fx3-luoyang.lhs11.com:ut": "${ENV(USERTOKEN)}",
                    "SERVERID": "cf2cc9c8ac39585fc0a0e28bf7f6523d|1639819158|1639819157",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.status", "success")
        ),
        Step(
            RunRequest("/v1/fxc4-api/coupon/triggerUnGet")
            .get("https://fx3-luoyang.lhs11.com/v1/fxc4-api/coupon/triggerUnGet")
            .with_params(**{"isAll": "true"})
            .with_headers(
                **{
                    "user-token": "${ENV(USERTOKEN)}",
                    "frontendappid": "wx8826cf59748f9d5b",
                    "env": "WXMP",
                    "user-agent": "Mozilla/5.0 (Linux; Android 6.0.1; MuMu Build/V417IR; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/68.0.3440.70 Mobile Safari/537.36 MMWEBID/77 MicroMessenger/7.0.22.1820(0x27001636) Process/tools WeChat/arm32 Weixin NetType/WIFI Language/zh_CN ABI/arm32",
                    "content-type": "application/json",
                    "accept": "*/*",
                    "referer": "https://fx3-luoyang.lhs11.com/fxc4-h5/",
                    "accept-encoding": "gzip, deflate",
                    "accept-language": "zh-CN,en-US;q=0.9",
                    "x-requested-with": "com.tencent.mm",
                }
            )
            .with_cookies(
                **{
                    "nginx-sticky": "1639816270.912.2299.391140",
                    "fx3-guangzhou.lhs11.com:ut": "${ENV(USERTOKEN)}",
                    "gr_user_id": "ff717bba-711e-4486-8fe1-ee35006320cd",
                    "fx3-pidu.lhs11.com:ut": "${ENV(USERTOKEN)}",
                    "fx3-luoyang.lhs11.com:ut": "${ENV(USERTOKEN)}",
                    "SERVERID": "cf2cc9c8ac39585fc0a0e28bf7f6523d|1639819158|1639819157",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.status", "success")
        ),
        Step(
            RunRequest("/v1/fxc4-api/customer/getCustomerInfo")
            .get("https://fx3-luoyang.lhs11.com/v1/fxc4-api/customer/getCustomerInfo")
            .with_headers(
                **{
                    "user-token": "${ENV(USERTOKEN)}",
                    "frontendappid": "wx8826cf59748f9d5b",
                    "env": "WXMP",
                    "user-agent": "Mozilla/5.0 (Linux; Android 6.0.1; MuMu Build/V417IR; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/68.0.3440.70 Mobile Safari/537.36 MMWEBID/77 MicroMessenger/7.0.22.1820(0x27001636) Process/tools WeChat/arm32 Weixin NetType/WIFI Language/zh_CN ABI/arm32",
                    "content-type": "application/json",
                    "accept": "*/*",
                    "referer": "https://fx3-luoyang.lhs11.com/fxc4-h5/",
                    "accept-encoding": "gzip, deflate",
                    "accept-language": "zh-CN,en-US;q=0.9",
                    "x-requested-with": "com.tencent.mm",
                }
            )
            .with_cookies(
                **{
                    "nginx-sticky": "1639816270.912.2299.391140",
                    "fx3-guangzhou.lhs11.com:ut": "${ENV(USERTOKEN)}",
                    "gr_user_id": "ff717bba-711e-4486-8fe1-ee35006320cd",
                    "fx3-pidu.lhs11.com:ut": "${ENV(USERTOKEN)}",
                    "fx3-luoyang.lhs11.com:ut": "${ENV(USERTOKEN)}",
                    "SERVERID": "cf2cc9c8ac39585fc0a0e28bf7f6523d|1639819158|1639819157",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.status", "success")
        ),
        Step(
            RunRequest("/v1/fxc4-api/home/getShelfP")
            .get("https://fx3-luoyang.lhs11.com/v1/fxc4-api/home/getShelfP")
            .with_params(
                **{
                    "currentCityId": "95",
                    "distributorLevel": "0",
                    "rebateDown": "-1",
                    "rebateUp": "-1",
                    "simplePageParam": "50,1",
                    "superRebateDown": "-1",
                }
            )
            .with_headers(
                **{
                    "user-token": "${ENV(USERTOKEN)}",
                    "frontendappid": "wx8826cf59748f9d5b",
                    "env": "WXMP",
                    "user-agent": "Mozilla/5.0 (Linux; Android 6.0.1; MuMu Build/V417IR; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/68.0.3440.70 Mobile Safari/537.36 MMWEBID/77 MicroMessenger/7.0.22.1820(0x27001636) Process/tools WeChat/arm32 Weixin NetType/WIFI Language/zh_CN ABI/arm32",
                    "content-type": "application/json",
                    "accept": "*/*",
                    "referer": "https://fx3-luoyang.lhs11.com/fxc4-h5/",
                    "accept-encoding": "gzip, deflate",
                    "accept-language": "zh-CN,en-US;q=0.9",
                    "x-requested-with": "com.tencent.mm",
                }
            )
            .with_cookies(
                **{
                    "nginx-sticky": "1639816270.912.2299.391140",
                    "fx3-guangzhou.lhs11.com:ut": "${ENV(USERTOKEN)}",
                    "gr_user_id": "ff717bba-711e-4486-8fe1-ee35006320cd",
                    "fx3-pidu.lhs11.com:ut": "${ENV(USERTOKEN)}",
                    "fx3-luoyang.lhs11.com:ut": "${ENV(USERTOKEN)}",
                    "SERVERID": "cf2cc9c8ac39585fc0a0e28bf7f6523d|1639819158|1639819157",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.status", "success")
        ),
        Step(
            RunRequest("/v1/fxc4-api/home/getShelfON")
            .get("https://fx3-luoyang.lhs11.com/v1/fxc4-api/home/getShelfON")
            .with_params(
                **{
                    "currentCityId": "95",
                    "distributorLevel": "0",
                    "rebateDown": "-1",
                    "rebateUp": "-1",
                    "simplePageParam": "50,1",
                    "superRebateDown": "-1",
                }
            )
            .with_headers(
                **{
                    "user-token": "${ENV(USERTOKEN)}",
                    "frontendappid": "wx8826cf59748f9d5b",
                    "env": "WXMP",
                    "user-agent": "Mozilla/5.0 (Linux; Android 6.0.1; MuMu Build/V417IR; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/68.0.3440.70 Mobile Safari/537.36 MMWEBID/77 MicroMessenger/7.0.22.1820(0x27001636) Process/tools WeChat/arm32 Weixin NetType/WIFI Language/zh_CN ABI/arm32",
                    "content-type": "application/json",
                    "accept": "*/*",
                    "referer": "https://fx3-luoyang.lhs11.com/fxc4-h5/",
                    "accept-encoding": "gzip, deflate",
                    "accept-language": "zh-CN,en-US;q=0.9",
                    "x-requested-with": "com.tencent.mm",
                }
            )
            .with_cookies(
                **{
                    "nginx-sticky": "1639816270.912.2299.391140",
                    "fx3-guangzhou.lhs11.com:ut": "${ENV(USERTOKEN)}",
                    "gr_user_id": "ff717bba-711e-4486-8fe1-ee35006320cd",
                    "fx3-pidu.lhs11.com:ut": "${ENV(USERTOKEN)}",
                    "fx3-luoyang.lhs11.com:ut": "${ENV(USERTOKEN)}",
                    "SERVERID": "cf2cc9c8ac39585fc0a0e28bf7f6523d|1639819158|1639819157",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.status", "success")
        ),
    ]


if __name__ == "__main__":
    TestCaseFxc4Homepage().test_start()
