# NOTE: Generated By HttpRunner v3.1.6
# FROM: har\test_notice.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseTestNotice(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/v1/fxc4-api/order/movie/notice")
            .post("https://fx3t-ysqg.lhs11.com/v1/fxc4-api/order/movie/notice")
            .with_headers(
                **{
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36",
                    "user-token": "",
                    "content-type": "application/json",
                }
            )
            .with_cookies(
                **{
                    "usertoken": '"2ui0UkpGUF7nWkP025xG25_0257@"',
                }
            )
            .with_json(
                {
                    "customerId": "24191924",
                    "parentId": "",
                    "portalId": 9001,
                    "ticketType": "0",
                    "buyCount": 1,
                    "channel": "NanLiMovie",
                    "costPrice": 25,
                    "cutPrice": 1.0,
                    "domain": "xxxxx",
                    "marketPrice": 1.0,
                    "mobile": "13128629906",
                    "orderNo": "${order_id()}",
                    "orderTime": "${order_time()}",
                    "remark": "test01",
                    "sellPrice": 39.6,
                    "status":6,
                    "ticketCodeInfoList": [
                        {
                            "codeImgUrl": "https://nlps.nldyp.com/uploads/tickets/20220211/6205d41fbd68a.png",
                            "seatMapUrl": "https://nlps.nldyp.com/uploads/tickets/20220211/6JFPw4v8550q7GScL7GFezcAi3IP1VgFxhFff7xN.jpg",
                            "voucherCode": "${voucherCode()}",
                        },
                        {
                            "codeImgUrl": "https://nlps.nldyp.com/uploads/tickets/20220211/6205d41fbd68a.png",
                            "seatMapUrl": "https://nlps.nldyp.com/uploads/tickets/20220211/6JFPw4v8550q7GScL7GFezcAi3IP1VgFxhFff7xN.jpg",
                            "voucherCode": "${voucherCode()}",
                        }
                    ],
                    "ticketInfo": {
                        "cinemaAddress": "海珠区宝岗大道498号601房602房（自编A6-01a、A6-01b、A6-01c、A6-01d、A6-01e号铺",
                        "cinemaName": "万达影城(海珠广百新一城店)",
                        "cityName": "广州市",
                        "cover": "https://oss.lhs11.com/product_imgs/9DA5DD0738EABF17.jpg",
                        "filmLanguage": "原版",
                        "movieName": "这个杀手不太冷静",
                        "movieType": "成人",
                        "playTime": "2022-02-15 11:30:00",
                        "screensName": "7号激光厅（免费停车2小时）",
                        "screensType": "3D",
                        "seatName": "7排8座|7排9座 ",
                    },
                    "totalPrice": 39.6,
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.status", "success")
            .assert_equal("body.result", 200)
        ),
    ]


if __name__ == "__main__":
    # for i in range(50):
    TestCaseTestNotice().test_start()
