# NOTE: Generated By HttpRunner v3.1.6
# FROM: har\dzmProduct.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseDzmproduct(HttpRunner):

    config = Config("testcase description").verify(False).base_url("${ENV(P_FXM_URL)}")

    teststeps = [
        Step(
            RunRequest("获取电子码产品基本信息")
            .post("/dzm/services/local/dzm/product/product.japi")
            .with_headers(
                **{
                    "content-type": "application/json",
                    "user-agent": "${ENV(USER_AGENT)}",
                }
            )
            .with_cookies(
                **{
                    "RSESSIONID": "${ENV(P_COOKIE)}",
                }
            )
            .with_json(
                {
                    "method": "query",
                    "params": {
                        "variables": {
                            "id": "277295",
                            "etime": "2022-03-10",
                            "property": 0,
                            "productSource": 0,
                        },
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("获取电子码基础型号")
            .post("/dzm/services/local/dzm/product/productSpec.japi")
                .with_headers(
                **{
                    "content-type": "application/json",
                    "user-agent": "${ENV(USER_AGENT)}",
                }
            )
                .with_cookies(
                **{
                    "RSESSIONID": "${ENV(P_COOKIE)}",
                }
            )
            .with_json(
                {
                    "method": "query",
                    "params": {
                        "variables": {
                            "prid": "277295",
                        },
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("获取电子码产品的组合规格")
            .post(
                "/dzm/services/local/dzm/product/productSpecBox.japi"
            )
                .with_headers(
                **{
                    "content-type": "application/json",
                    "user-agent": "${ENV(USER_AGENT)}",
                }
            )
                .with_cookies(
                **{
                    "RSESSIONID": "${ENV(P_COOKIE)}",
                }
            )
            .with_json(
                {
                    "order": "asc",
                    "method": "query",
                    "params": {"pagenumber": 1, "variables": {"productId": "277295"}},
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("获取电子码产品的配额")
            .post(
                "/dzm/services/local/dzm/product/productAlloc.japi"
            )
            .with_headers(
                **{
                    "content-type": "application/json",
                    "user-agent": "${ENV(USER_AGENT)}",
                }
            )
            .with_cookies(
                **{
                    "RSESSIONID": "${ENV(P_COOKIE)}",
                }
            )
            .with_json(
                {
                    "order": "asc",
                    "method": "query",
                    "params": {"pagenumber": 1, "variables": {"productId": "277295"}},
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseDzmproduct().test_start()
