# NOTE: Generated By HttpRunner v3.1.6
# FROM: har\update_product.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase
from p_fxm_product_test import  TestCasePFxmProduct


class TestCaseUpdateProduct(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunTestCase("request with functions")
            .with_variables(
                **{"foo1": "testcase_ref_bar1", "expect_foo1": "testcase_ref_bar1"}
            )
            .call(TestCasePFxmProduct)
            .export(*["remark", "product_name"])
        ),
        Step(
            RunRequest("/fxm/services/local/fxm/product/product.japi")
            .post("https://mt.lhs11.com/fxm/services/local/fxm/product/product.japi")
            .with_headers(
                **{
                    "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko)"
                                  " Chrome/98.0.4758.102 Safari/537.36",
                }
            )
            .with_cookies(
                **{
                    "RSESSIONID": "R01O9TSRZ0E6F6NG8NX65J2BAMR9O50",
                }
            )
            .with_json(
                {"method": "update_product_base", "params": {
                    "variables": {"status": "0", "business": "", "sourcing_id": "22424149",
                                  "name": "$product_name",
                                  "min_limit_count": "1", "limit_count": "9999", "is_sub_wechat": 1,
                                  "order_min_limit_count": "", "order_max_limit_count": "", "country": "0",
                                  "province": "29", "city": "1292",
                                  "product_addr": "浣涘北涓夋按鏂板姩鍔涘箍鍦哄笇灏旈】娆㈡湅閰掑簵涓夋ゼ娆㈡湅椁愬巺 ", "send_type": "1",
                                  "send_time": "", "delay_day": "", "delay_hour": "", "delay_minute": "",
                                  "delay_rebate_day": "7", "refund_period": "7", "pay_ways": "3.2.2",
                                  "img_main": "BC1704C5D6A46EF8.gif", "img_main_small": "BECACD0A4C1153D6.jpg",
                                  "img_main_banner": "", "img_poster": "800647963864A9E7.png", "img_poster_title": "",
                                  "img_list": "B552B2A7E1BEE181.jpg,31111DE9DD60EFF9.jpg,9E8632B56BEDBF29.jpg,A357A43273B3F64F.jpg,196715324BA73943.jpg,F4F08A7B6E360F44.jpg,0482545923BA0939.jpg",
                                  "imgz": "0482545923BA0939.jpg", "performance_tag": "8",
                                  "begin_time": "2022-03-04 10:49:07", "end_time": "2022-06-29 23:59:59",
                                  "off_shelf_time": "2022-06-30 06:00:00", "browse": "0", "is_show_countdown": 1,
                                  "buy_sms": "", "peers_buy_sms": "", "send_sms": "", "remark": "$remark",
                                  "countdown_value": "72", "img_poster_type": 0, "lat": "23.172411",
                                  "lon": "112.870201", "rebate_strategy": "1", "product_class": "dzm",
                                  "product_id": 5463, "product_code": "5YNAR5", "label_ids": "",
                                  "is_display_pageviews": 0, "offset_pageviews": 0}}}
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseUpdateProduct().test_start()
